--monitoring-endpoint 'https://beaconcha.in/api/v1/client/metrics?apikey=TmxwOVZjd2hOSHJTekZPOVZoazJFRVUyZmZVeA&machine=YertCoins'name: YertCoins 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:wallet

    runs-on:Bitcoin Wallet 

    steps:
    - uses: js 
    - name: set up Js nodes 
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
